base_port: 9000
versions:
  v8.3.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.3.0-ce.0_amd64.deb/download'
  v8.3.8: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.3.8-ce.0_amd64.deb/download'
  v8.3.9: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.3.9-ce.0_amd64.deb/download'
  v8.4.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.4.0-ce.0_amd64.deb/download'
  v8.4.9: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.4.9-ce.0_amd64.deb/download'
  v8.4.10: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.4.10-ce.0_amd64.deb/download'
  v8.5.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.5.0-ce.0_amd64.deb/download'
  v8.5.11: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.5.11-ce.0_amd64.deb/download'
  v8.5.12: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.5.12-ce.0_amd64.deb/download'
  v8.6.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.6.0-ce.0_amd64.deb/download'
  v8.6.7: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.6.7-ce.0_amd64.deb/download'
  v8.6.8: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.6.8-ce.0_amd64.deb/download'
  v8.7.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.7.0-ce.0_amd64.deb/download'
  v8.7.3: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.7.3-ce.0_amd64.deb/download'
  v8.7.6: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.7.6-ce.0_amd64.deb/download'
  v8.8.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.0-ce.0_amd64.deb/download'
  v8.8.2: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.2-ce.0_amd64.deb/download'
  v8.8.4: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.4-ce.0_amd64.deb/download'
  v8.8.5: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.5-ce.0_amd64.deb/download'
  v8.8.7: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.8.7-ce.0_amd64.deb/download'
  v8.9.6: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.9.6-ce.0_amd64.deb/download'
  v8.10.5: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.10.5-ce.0_amd64.deb/download'
  v8.11.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.0-ce.0_amd64.deb/download'
  v8.11.2: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.2-ce.0_amd64.deb/download'
  v8.11.3: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.3-ce.0_amd64.deb/download'
  v8.11.4: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.4-ce.0_amd64.deb/download'
  v8.11.5: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.5-ce.0_amd64.deb/download'
  v8.11.6: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.6-ce.0_amd64.deb/download'
  v8.11.7: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.11.7-ce.0_amd64.deb/download'
  v8.12.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.12.0-ce.0_amd64.deb/download'
  v8.12.4: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.12.4-ce.0_amd64.deb/download'
  v8.12.6: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.12.6-ce.0_amd64.deb/download'
  v8.12.7: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.12.7-ce.0_amd64.deb/download'
  v8.13.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.13.0-ce.0_amd64.deb/download'
  v8.13.3: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.13.3-ce.0_amd64.deb/download'
  v8.13.11: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.13.11-ce.0_amd64.deb/download'
  v8.13.12: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.13.12-ce.0_amd64.deb/download'
  v8.14.2: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.14.2-ce.0_amd64.deb/download'
  v8.14.6: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.14.6-ce.0_amd64.deb/download'
  v8.14.7: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.14.7-ce.0_amd64.deb/download'
  v8.14.9: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.14.9-ce.0_amd64.deb/download'
  v8.15.2: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.15.2-ce.0_amd64.deb/download'
  v8.15.4: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.15.4-ce.0_amd64.deb/download'
  v8.15.5: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.15.5-ce.0_amd64.deb/download'
  v8.15.6: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.15.6-ce.0_amd64.deb/download'
  v8.15.7: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.15.7-ce.0_amd64.deb/download'
  v8.16.2: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.16.2-ce.0_amd64.deb/download'
  v8.16.4: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.16.4-ce.0_amd64.deb/download'
  v8.16.5: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.16.5-ce.0_amd64.deb/download'
  v8.16.6: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.16.6-ce.0_amd64.deb/download'
  v8.16.7: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.16.7-ce.0_amd64.deb/download'
  v8.17.2: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.17.2-ce.0_amd64.deb/download'
  v8.17.3: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.17.3-ce.0_amd64.deb/download'
  v8.15.8: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.15.8-ce.0_amd64.deb/download'
  v8.16.8: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.16.8-ce.0_amd64.deb/download'
  v8.17.4: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_8.17.4-ce.0_amd64.deb/download'
  v9.0.0: 'https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/precise/gitlab-ce_9.0.0-ce.0_amd64.deb/download'
